apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded "password"
  API_KEY: YXBpa2V5MTIzNDU=  # Base64 encoded "apikey12345"
